// Generated by pnpm brand:generate from brand/ember-lens.svg.
export const BRAND_MARK_PATH =
  "M14.76 1.5C14.76 6.3 21.2 8.1 21.2 14A9.2 8 0 0 1 2.8 14C2.8 11.1 4.18 8.9 6.48 7.2C6.342 8.3 6.94 8.8 8.09 9.2C8.136 6.2 10.896 3.7 14.76 1.5ZM14.65 9.410065A5.3 5.3 0 1 0 14.65 18.589935A4.8 4.8 0 0 1 14.65 9.410065Z";
export const BRAND_ORANGE = "#E95E00";
export const BRAND_DARK = "#1F1A15";
